# Generated by Django 4.2.7 on 2023-11-11 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventasProductos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('fecha_pago', models.DateField()),
                ('ventaProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventasProductos.ventasproductos')),
            ],
        ),
    ]
