# Generated by Django 4.2.7 on 2023-11-11 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiposEspumillas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistenciasEspumillas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('tipoEspumilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiposEspumillas.tiposespumillas')),
            ],
        ),
    ]
