# Generated by Django 4.2.7 on 2023-11-11 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('telas_colores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprasTelasColores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.compras')),
                ('tela_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telas_colores.telascolores')),
            ],
        ),
    ]
