# Generated by Django 4.2.4 on 2023-12-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detallesNoTapizados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesnotapizados',
            name='cantidad_producto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detallesnotapizados',
            name='cantidad_tipoMaterial',
            field=models.IntegerField(default=0),
        ),
    ]
