# Generated by Django 4.2.4 on 2023-12-15 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiposMateriales', '0001_initial'),
        ('detallesNoTapizados', '0002_detallesnotapizados_cantidad_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesnotapizados',
            name='tipoMaterial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tiposMateriales.tiposmateriales'),
            preserve_default=False,
        ),
    ]
