# Generated by Django 4.2.7 on 2023-11-10 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colores',
            options={'verbose_name': 'TipoTela', 'verbose_name_plural': 'TiposTelas'},
        ),
    ]
