# Generated by Django 4.2.7 on 2023-11-10 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colores', '0002_alter_colores_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colores',
            options={},
        ),
    ]
