# Generated by Django 4.2.7 on 2023-11-10 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiposTelas', '0001_initial'),
        ('productos', '0001_initial'),
        ('colores', '0003_alter_colores_options'),
        ('tiposEspumillas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesTapizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colores.colores')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productos')),
                ('tipoEspumilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiposEspumillas.tiposespumillas')),
                ('tipoTela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiposTelas.tipostelas')),
            ],
        ),
    ]
