# Generated by Django 4.2.7 on 2023-11-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detallesTapizados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallestapizados',
            name='cantidad_telasColores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detallestapizados',
            name='cantidad_tipoMaterial',
            field=models.IntegerField(default=0),
        ),
    ]
