# Generated by Django 4.2.4 on 2023-12-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detallesTapizados', '0002_detallestapizados_cantidad_telascolores_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallestapizados',
            old_name='cantidad_telasColores',
            new_name='cantidad_telaColor',
        ),
        migrations.AddField(
            model_name='detallestapizados',
            name='cantidad_tipoEspumilla',
            field=models.IntegerField(default=0),
        ),
    ]
