# Generated by Django 4.2.4 on 2023-12-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detallesTapizados', '0003_rename_cantidad_telascolores_detallestapizados_cantidad_telacolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallestapizados',
            name='cantidad_producto',
            field=models.IntegerField(default=0),
        ),
    ]
