# Generated by Django 4.2.4 on 2023-12-16 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiposTelas', '0001_initial'),
        ('colores', '0003_alter_colores_options'),
        ('detallesTapizados', '0005_remove_detallestapizados_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallestapizados',
            name='telaColor',
        ),
        migrations.AddField(
            model_name='detallestapizados',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='colores.colores'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallestapizados',
            name='tipoTela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tiposTelas.tipostelas'),
            preserve_default=False,
        ),
    ]
