# Generated by Django 4.2.7 on 2023-11-11 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telas_colores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistenciasTelasColores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('tela_Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telas_colores.telascolores')),
            ],
        ),
    ]
